### ISSUE TITLE
有没有教程或者类似说明？

### ISSUE THREAD

**Issue by sunhawk2100** [dedededede/datax_web_ui#1]
有没有教程或者类似说明？这个不错，不知道有没有教程以及其他安装文档？

**Comment by dedededede** [comment]
这个我也是在开发中，目前还没有教程。



406588357@qq.com
 
发件人： Linksame Docker
发送时间： 2017-04-26 14:37
收件人： dedededede/datax_web_ui
抄送： Subscribed
主题： [dedededede/datax_web_ui] 有没有教程或者类似说明？ (#1)
有没有教程或者类似说明？这个不错，不知道有没有教程以及其他安装文档？
